import type { CoreStore } from "./types";

export const coreStore: CoreStore = {
  tenants: [
    {
      id: "tenant_kynovia_labs",
      legalName: "Kynovia Labs Tecnologia Ltda",
      tradeName: "Kynovia Labs",
      document: "00.000.000/0001-00",
      email: "ops@kynovia.com.br",
      phone: "+55 11 4000-0000",
      status: "active",
      createdAt: "2026-07-01T10:00:00Z",
      updatedAt: "2026-07-15T08:42:00Z",
    },
    {
      id: "tenant_northwind_cloud",
      legalName: "Northwind Cloud Servicos Ltda",
      tradeName: "Northwind Cloud",
      document: "11.111.111/0001-11",
      email: "admin@northwind.dev",
      phone: "+55 11 4111-1111",
      status: "pending",
      createdAt: "2026-07-10T12:00:00Z",
      updatedAt: "2026-07-12T09:00:00Z",
    },
    {
      id: "tenant_atlas_operations",
      legalName: "Atlas Operations S.A.",
      tradeName: "Atlas Operations",
      document: "22.222.222/0001-22",
      email: "admin@atlasops.com",
      phone: "+55 11 4222-2222",
      status: "active",
      createdAt: "2026-06-05T09:00:00Z",
      updatedAt: "2026-07-14T17:18:00Z",
    },
    {
      id: "tenant_orion_services",
      legalName: "Orion Services Ltda",
      tradeName: "Orion Services",
      document: "33.333.333/0001-33",
      email: "admin@orionservices.com",
      phone: "+55 11 4333-3333",
      status: "suspended",
      createdAt: "2026-05-22T09:00:00Z",
      updatedAt: "2026-07-01T10:04:00Z",
    },
  ],
  users: [
    {
      id: "user_amanda",
      name: "Amanda Rocha",
      email: "amanda@kynovia.com.br",
      status: "active",
      lastAccessAt: "2026-07-15T08:42:00Z",
      createdAt: "2026-07-01T10:00:00Z",
      updatedAt: "2026-07-15T08:42:00Z",
    },
    {
      id: "user_bruno",
      name: "Bruno Martins",
      email: "bruno@northwind.dev",
      status: "invited",
      lastAccessAt: null,
      createdAt: "2026-07-10T12:00:00Z",
      updatedAt: "2026-07-10T12:00:00Z",
    },
    {
      id: "user_clara",
      name: "Clara Nunes",
      email: "clara@atlasops.com",
      status: "active",
      lastAccessAt: "2026-07-14T17:18:00Z",
      createdAt: "2026-06-05T09:00:00Z",
      updatedAt: "2026-07-14T17:18:00Z",
    },
    {
      id: "user_diego",
      name: "Diego Almeida",
      email: "diego@orionservices.com",
      status: "suspended",
      lastAccessAt: "2026-07-01T10:04:00Z",
      createdAt: "2026-05-22T09:00:00Z",
      updatedAt: "2026-07-01T10:04:00Z",
    },
  ],
  memberships: [
    {
      id: "membership_amanda_kynovia",
      tenantId: "tenant_kynovia_labs",
      userId: "user_amanda",
      status: "active",
      invitedBy: null,
      joinedAt: "2026-07-01T10:00:00Z",
      createdAt: "2026-07-01T10:00:00Z",
      updatedAt: "2026-07-15T08:42:00Z",
    },
    {
      id: "membership_bruno_northwind",
      tenantId: "tenant_northwind_cloud",
      userId: "user_bruno",
      status: "invited",
      invitedBy: "user_amanda",
      joinedAt: null,
      createdAt: "2026-07-10T12:00:00Z",
      updatedAt: "2026-07-10T12:00:00Z",
    },
    {
      id: "membership_clara_atlas",
      tenantId: "tenant_atlas_operations",
      userId: "user_clara",
      status: "active",
      invitedBy: "user_amanda",
      joinedAt: "2026-06-05T09:00:00Z",
      createdAt: "2026-06-05T09:00:00Z",
      updatedAt: "2026-07-14T17:18:00Z",
    },
    {
      id: "membership_diego_orion",
      tenantId: "tenant_orion_services",
      userId: "user_diego",
      status: "suspended",
      invitedBy: "user_amanda",
      joinedAt: "2026-05-22T09:00:00Z",
      createdAt: "2026-05-22T09:00:00Z",
      updatedAt: "2026-07-01T10:04:00Z",
    },
  ],
  permissions: [
    { id: "perm_users_view", code: "platform.users.view", description: "Visualizar usuários." },
    { id: "perm_users_create", code: "platform.users.create", description: "Criar usuários." },
    { id: "perm_users_update", code: "platform.users.update", description: "Atualizar usuários." },
    { id: "perm_users_delete", code: "platform.users.delete", description: "Remover usuários." },
    { id: "perm_tenants_manage", code: "platform.tenants.manage", description: "Gerenciar empresas." },
    { id: "perm_roles_manage", code: "platform.roles.manage", description: "Gerenciar papéis." },
    { id: "perm_settings_manage", code: "platform.settings.manage", description: "Gerenciar configurações." },
    { id: "perm_contracts_view", code: "platform.contracts.view", description: "Visualizar contratos." },
    { id: "perm_contracts_manage", code: "platform.contracts.manage", description: "Gerenciar contratos." },
    { id: "perm_audit_view", code: "platform.audit.view", description: "Visualizar auditoria." },
  ],
  roles: [
    {
      id: "role_super_admin",
      tenantId: null,
      name: "super_admin",
      scope: "global",
      description: "Administração completa da plataforma e operação do Core.",
      permissionIds: [
        "perm_users_view",
        "perm_users_create",
        "perm_users_update",
        "perm_users_delete",
        "perm_tenants_manage",
        "perm_roles_manage",
        "perm_settings_manage",
        "perm_contracts_view",
        "perm_contracts_manage",
        "perm_audit_view",
      ],
    },
    {
      id: "role_platform_admin",
      tenantId: null,
      name: "platform_admin",
      scope: "global",
      description: "Gestão operacional sem acesso a configurações sensíveis.",
      permissionIds: [
        "perm_users_view",
        "perm_users_create",
        "perm_users_update",
        "perm_tenants_manage",
        "perm_roles_manage",
        "perm_contracts_view",
        "perm_audit_view",
      ],
    },
    {
      id: "role_tenant_admin",
      tenantId: null,
      name: "tenant_admin",
      scope: "tenant",
      description: "Administração completa dentro da empresa ativa.",
      permissionIds: [
        "perm_users_view",
        "perm_users_create",
        "perm_users_update",
        "perm_tenants_manage",
        "perm_roles_manage",
        "perm_contracts_view",
      ],
    },
    {
      id: "role_tenant_manager",
      tenantId: null,
      name: "tenant_manager",
      scope: "tenant",
      description: "Gestão operacional dentro da empresa ativa.",
      permissionIds: ["perm_users_view", "perm_users_update", "perm_contracts_view"],
    },
    {
      id: "role_tenant_user",
      tenantId: null,
      name: "tenant_user",
      scope: "tenant",
      description: "Uso padrão de recursos liberados para a empresa.",
      permissionIds: ["perm_users_view"],
    },
    {
      id: "role_viewer",
      tenantId: null,
      name: "viewer",
      scope: "tenant",
      description: "Acesso de leitura para auditoria e acompanhamento.",
      permissionIds: ["perm_users_view", "perm_contracts_view"],
    },
  ],
  userRoles: [
    { id: "user_role_amanda_super", tenantId: "tenant_kynovia_labs", userId: "user_amanda", roleId: "role_super_admin" },
    { id: "user_role_bruno_admin", tenantId: "tenant_northwind_cloud", userId: "user_bruno", roleId: "role_tenant_admin" },
    { id: "user_role_clara_manager", tenantId: "tenant_atlas_operations", userId: "user_clara", roleId: "role_tenant_manager" },
    { id: "user_role_diego_user", tenantId: "tenant_orion_services", userId: "user_diego", roleId: "role_tenant_user" },
  ],
  products: [
    {
      id: "product_core_platform",
      code: "core-platform",
      name: "Core Platform",
      description: "Produto estrutural da plataforma Kynovia SaaS Core.",
      status: "active",
    },
  ],
  modules: [
    {
      id: "module_identity",
      productId: "product_core_platform",
      code: "identity",
      name: "Identidade e sessão",
      description: "Autenticação, sessões e provedores.",
      status: "active",
    },
    {
      id: "module_tenant_admin",
      productId: "product_core_platform",
      code: "tenant-admin",
      name: "Administração de empresas",
      description: "Gestão de tenants, usuários e vínculos.",
      status: "active",
    },
    {
      id: "module_contracts",
      productId: "product_core_platform",
      code: "contracts",
      name: "Contratos e assinaturas",
      description: "Planos, contratos, assinaturas e limites.",
      status: "pending",
    },
    {
      id: "module_audit",
      productId: "product_core_platform",
      code: "audit",
      name: "Auditoria",
      description: "Eventos de acesso e alterações administrativas.",
      status: "planned",
    },
  ],
  plans: [
    {
      id: "plan_platform_pro",
      code: "platform-pro",
      name: "Platform Pro",
      description: "Plano profissional para tenants ativos.",
      billingCycle: "monthly",
      status: "active",
      maximumUsers: 100,
    },
    {
      id: "plan_core_trial",
      code: "core-trial",
      name: "Core Trial",
      description: "Plano de avaliação para onboarding.",
      billingCycle: "trial",
      status: "active",
      maximumUsers: 10,
    },
    {
      id: "plan_enterprise",
      code: "enterprise",
      name: "Enterprise",
      description: "Plano corporativo com limites ampliados.",
      billingCycle: "quarterly",
      status: "active",
      maximumUsers: 500,
    },
    {
      id: "plan_platform_basic",
      code: "platform-basic",
      name: "Platform Basic",
      description: "Plano base para operações menores.",
      billingCycle: "monthly",
      status: "active",
      maximumUsers: 25,
    },
  ],
  contracts: [
    {
      id: "contract_kynovia",
      tenantId: "tenant_kynovia_labs",
      planId: "plan_platform_pro",
      contractNumber: "CTR-2026-0001",
      billingCycle: "monthly",
      startDate: "2026-07-01",
      endDate: "2026-08-01",
      renewalDate: "2026-08-20",
      status: "active",
      notes: null,
    },
    {
      id: "contract_northwind",
      tenantId: "tenant_northwind_cloud",
      planId: "plan_core_trial",
      contractNumber: "CTR-2026-0002",
      billingCycle: "trial",
      startDate: "2026-07-10",
      endDate: "2026-07-30",
      renewalDate: "2026-07-30",
      status: "pending",
      notes: "Trial em onboarding.",
    },
    {
      id: "contract_atlas",
      tenantId: "tenant_atlas_operations",
      planId: "plan_enterprise",
      contractNumber: "CTR-2026-0003",
      billingCycle: "quarterly",
      startDate: "2026-07-05",
      endDate: "2026-10-05",
      renewalDate: "2026-10-05",
      status: "active",
      notes: null,
    },
    {
      id: "contract_orion",
      tenantId: "tenant_orion_services",
      planId: "plan_platform_basic",
      contractNumber: "CTR-2026-0004",
      billingCycle: "monthly",
      startDate: "2026-06-22",
      endDate: "2026-07-22",
      renewalDate: "2026-07-22",
      status: "suspended",
      notes: "Acesso suspenso por status comercial.",
    },
  ],
  contractItems: [
    {
      id: "contract_item_kynovia_platform",
      tenantId: "tenant_kynovia_labs",
      contractId: "contract_kynovia",
      productId: "product_core_platform",
      moduleId: null,
      itemType: "platform_access",
      description: "Acesso à plataforma Core para o tenant.",
      billingModel: "flat",
      quantity: 1,
      unitPrice: 499,
      totalPrice: 499,
      startsAt: "2026-07-01",
      endsAt: "2026-08-01",
      status: "active",
      metadata: {},
    },
    {
      id: "contract_item_kynovia_resource",
      tenantId: "tenant_kynovia_labs",
      contractId: "contract_kynovia",
      productId: "product_core_platform",
      moduleId: "module_contracts",
      itemType: "external_resource",
      description: "Cobertura comercial para recurso externo genérico.",
      billingModel: "per_resource",
      quantity: 3,
      unitPrice: 120,
      totalPrice: 360,
      startsAt: "2026-07-01",
      endsAt: "2026-08-01",
      status: "active",
      metadata: { resourceType: "workspace" },
    },
    {
      id: "contract_item_atlas_platform",
      tenantId: "tenant_atlas_operations",
      contractId: "contract_atlas",
      productId: "product_core_platform",
      moduleId: null,
      itemType: "platform_access",
      description: "Acesso corporativo à plataforma Core.",
      billingModel: "flat",
      quantity: 1,
      unitPrice: 1499,
      totalPrice: 1499,
      startsAt: "2026-07-05",
      endsAt: "2026-10-05",
      status: "active",
      metadata: {},
    },
  ],
  contractScopes: [
    {
      id: "contract_scope_kynovia_workspace_a",
      tenantId: "tenant_kynovia_labs",
      contractId: "contract_kynovia",
      contractItemId: "contract_item_kynovia_resource",
      productId: "product_core_platform",
      resourceType: "workspace",
      resourceId: "workspace_alpha",
      resourceCode: "WKS-ALPHA",
      displayName: "Workspace Alpha",
      status: "active",
      startsAt: "2026-07-01",
      expiresAt: "2026-08-01",
      metadata: {},
    },
    {
      id: "contract_scope_kynovia_workspace_b",
      tenantId: "tenant_kynovia_labs",
      contractId: "contract_kynovia",
      contractItemId: "contract_item_kynovia_resource",
      productId: "product_core_platform",
      resourceType: "workspace",
      resourceId: "workspace_beta",
      resourceCode: "WKS-BETA",
      displayName: "Workspace Beta",
      status: "active",
      startsAt: "2026-07-01",
      expiresAt: "2026-08-01",
      metadata: {},
    },
  ],
  externalResources: [
    {
      id: "external_resource_kynovia_workspace_alpha",
      tenantId: "tenant_kynovia_labs",
      productId: "product_core_platform",
      resourceType: "workspace",
      externalId: "workspace_alpha",
      code: "WKS-ALPHA",
      displayName: "Workspace Alpha",
      status: "active",
      metadata: {},
    },
    {
      id: "external_resource_kynovia_workspace_beta",
      tenantId: "tenant_kynovia_labs",
      productId: "product_core_platform",
      resourceType: "workspace",
      externalId: "workspace_beta",
      code: "WKS-BETA",
      displayName: "Workspace Beta",
      status: "active",
      metadata: {},
    },
  ],
  subscriptions: [
    {
      id: "subscription_kynovia",
      tenantId: "tenant_kynovia_labs",
      contractId: "contract_kynovia",
      planId: "plan_platform_pro",
      status: "active",
      startedAt: "2026-07-01",
      currentPeriodStart: "2026-07-01",
      currentPeriodEnd: "2026-08-01",
      cancelledAt: null,
    },
    {
      id: "subscription_northwind",
      tenantId: "tenant_northwind_cloud",
      contractId: "contract_northwind",
      planId: "plan_core_trial",
      status: "trial",
      startedAt: "2026-07-10",
      currentPeriodStart: "2026-07-10",
      currentPeriodEnd: "2026-07-30",
      cancelledAt: null,
    },
    {
      id: "subscription_atlas",
      tenantId: "tenant_atlas_operations",
      contractId: "contract_atlas",
      planId: "plan_enterprise",
      status: "active",
      startedAt: "2026-07-05",
      currentPeriodStart: "2026-07-05",
      currentPeriodEnd: "2026-10-05",
      cancelledAt: null,
    },
    {
      id: "subscription_orion",
      tenantId: "tenant_orion_services",
      contractId: "contract_orion",
      planId: "plan_platform_basic",
      status: "suspended",
      startedAt: "2026-06-22",
      currentPeriodStart: "2026-06-22",
      currentPeriodEnd: "2026-07-22",
      cancelledAt: null,
    },
  ],
  entitlements: [
    {
      id: "entitlement_kynovia_identity",
      tenantId: "tenant_kynovia_labs",
      productId: "product_core_platform",
      moduleId: "module_identity",
      resourceType: null,
      resourceId: null,
      status: "active",
      source: "core",
      sourceId: null,
      startsAt: "2026-07-01",
      expiresAt: null,
      metadata: {},
    },
    {
      id: "entitlement_kynovia_tenant_admin",
      tenantId: "tenant_kynovia_labs",
      productId: "product_core_platform",
      moduleId: "module_tenant_admin",
      resourceType: null,
      resourceId: null,
      status: "active",
      source: "core",
      sourceId: null,
      startsAt: "2026-07-01",
      expiresAt: null,
      metadata: {},
    },
    {
      id: "entitlement_kynovia_contracts",
      tenantId: "tenant_kynovia_labs",
      productId: "product_core_platform",
      moduleId: "module_contracts",
      resourceType: null,
      resourceId: null,
      status: "active",
      source: "plan",
      sourceId: "plan_platform_pro",
      startsAt: "2026-07-01",
      expiresAt: "2026-08-01",
      metadata: {},
    },
    {
      id: "entitlement_kynovia_workspace_alpha",
      tenantId: "tenant_kynovia_labs",
      productId: "product_core_platform",
      moduleId: "module_contracts",
      resourceType: "workspace",
      resourceId: "workspace_alpha",
      status: "active",
      source: "contract",
      sourceId: "contract_item_kynovia_resource",
      startsAt: "2026-07-01",
      expiresAt: "2026-08-01",
      metadata: {},
    },
    {
      id: "entitlement_atlas_identity",
      tenantId: "tenant_atlas_operations",
      productId: "product_core_platform",
      moduleId: "module_identity",
      resourceType: null,
      resourceId: null,
      status: "active",
      source: "core",
      sourceId: null,
      startsAt: "2026-07-05",
      expiresAt: null,
      metadata: {},
    },
    {
      id: "entitlement_atlas_contracts",
      tenantId: "tenant_atlas_operations",
      productId: "product_core_platform",
      moduleId: "module_contracts",
      resourceType: null,
      resourceId: null,
      status: "active",
      source: "plan",
      sourceId: "plan_enterprise",
      startsAt: "2026-07-05",
      expiresAt: "2026-10-05",
      metadata: {},
    },
  ],
  usageLimits: [
    { id: "usage_kynovia_users", tenantId: "tenant_kynovia_labs", code: "maximum_users", limit: 100, used: 42 },
    { id: "usage_northwind_users", tenantId: "tenant_northwind_cloud", code: "maximum_users", limit: 10, used: 8 },
    { id: "usage_atlas_users", tenantId: "tenant_atlas_operations", code: "maximum_users", limit: 500, used: 67 },
    { id: "usage_orion_users", tenantId: "tenant_orion_services", code: "maximum_users", limit: 25, used: 19 },
  ],
  branding: [
    {
      id: "branding_kynovia",
      tenantId: "tenant_kynovia_labs",
      name: "Kynovia Labs",
      logoUrl: null,
      smallLogoUrl: null,
      faviconUrl: null,
      loginImageUrl: null,
      primaryColor: "#1E4066",
      secondaryColor: "#148779",
      supportEmail: "suporte@kynovia.com.br",
      supportPhone: "+55 11 4000-0000",
      termsUrl: null,
      privacyUrl: null,
    },
  ],
  auditLogs: [
    {
      id: "audit_tenant_created",
      tenantId: "tenant_kynovia_labs",
      actorUserId: "user_amanda",
      action: "tenant.created",
      entityType: "tenant",
      entityId: "tenant_kynovia_labs",
      metadata: {
        source: "mock",
        status: "active",
      },
      createdAt: "2026-07-15T08:42:00Z",
    },
    {
      id: "audit_user_invited",
      tenantId: "tenant_northwind_cloud",
      actorUserId: "user_amanda",
      action: "user.invited",
      entityType: "tenant_membership",
      entityId: "membership_bruno_northwind",
      metadata: {
        email: "bruno@northwind.dev",
        role: "tenant_admin",
      },
      createdAt: "2026-07-15T09:10:00Z",
    },
    {
      id: "audit_contract_suspended",
      tenantId: "tenant_orion_services",
      actorUserId: "user_amanda",
      action: "contract.suspended",
      entityType: "contract",
      entityId: "contract_orion",
      metadata: {
        reason: "commercial_status",
      },
      createdAt: "2026-07-15T10:05:00Z",
    },
    {
      id: "audit_entitlement_activated",
      tenantId: "tenant_atlas_operations",
      actorUserId: "user_clara",
      action: "entitlement.activated",
      entityType: "entitlement",
      entityId: "entitlement_atlas_contracts",
      metadata: {
        module: "contracts",
        source: "plan",
      },
      createdAt: "2026-07-15T11:22:00Z",
    },
  ],
};
